
VERSION=$(shell cat VERSION.txt)
BASENAME=WorldWeatherSymbols-$(VERSION)-png

ICONS := \
	CH_CloudHigh/CloudHigh_CH_1.svg	\
	CH_CloudHigh/CloudHigh_CH_2.svg	\
	CH_CloudHigh/CloudHigh_CH_3.svg	\
	CH_CloudHigh/CloudHigh_CH_4.svg	\
	CH_CloudHigh/CloudHigh_CH_5.svg	\
	CH_CloudHigh/CloudHigh_CH_6.svg	\
	CH_CloudHigh/CloudHigh_CH_7.svg	\
	CH_CloudHigh/CloudHigh_CH_8.svg	\
	CH_CloudHigh/CloudHigh_CH_9.svg	\
	CL_CloudLow/CloudLow_CL_1.svg	\
	CL_CloudLow/CloudLow_CL_2.svg	\
	CL_CloudLow/CloudLow_CL_3.svg	\
	CL_CloudLow/CloudLow_CL_4.svg	\
	CL_CloudLow/CloudLow_CL_5.svg	\
	CL_CloudLow/CloudLow_CL_6.svg	\
	CL_CloudLow/CloudLow_CL_7.svg	\
	CL_CloudLow/CloudLow_CL_8.svg	\
	CL_CloudLow/CloudLow_CL_8a.svg	\
	CL_CloudLow/CloudLow_CL_9.svg	\
	CM_CloudMedium/CloudMedium_CM_1.svg	\
	CM_CloudMedium/CloudMedium_CM_2.svg	\
	CM_CloudMedium/CloudMedium_CM_3.svg	\
	CM_CloudMedium/CloudMedium_CM_4.svg	\
	CM_CloudMedium/CloudMedium_CM_5.svg	\
	CM_CloudMedium/CloudMedium_CM_6.svg	\
	CM_CloudMedium/CloudMedium_CM_7.svg	\
	CM_CloudMedium/CloudMedium_CM_8.svg	\
	CM_CloudMedium/CloudMedium_CM_9.svg	\
	C_CloudGenus/CloudGenus_C_0.svg	\
	C_CloudGenus/CloudGenus_C_1.svg	\
	C_CloudGenus/CloudGenus_C_2.svg	\
	C_CloudGenus/CloudGenus_C_3.svg	\
	C_CloudGenus/CloudGenus_C_4.svg	\
	C_CloudGenus/CloudGenus_C_5.svg	\
	C_CloudGenus/CloudGenus_C_6.svg	\
	C_CloudGenus/CloudGenus_C_7.svg	\
	C_CloudGenus/CloudGenus_C_8.svg	\
	C_CloudGenus/CloudGenus_C_9.svg	\
	Ds_ShipDirection/ShipDirection_Ds.svg	\
	E_StateOfGround/StateOfGround_E_0.svg	\
	E_StateOfGround/StateOfGround_E_1.svg	\
	E_StateOfGround/StateOfGround_E_2.svg	\
	E_StateOfGround/StateOfGround_E_3.svg	\
	E_StateOfGround/StateOfGround_E_4.svg	\
	E_StateOfGround/StateOfGround_E_5.svg	\
	E_StateOfGround/StateOfGround_E_6.svg	\
	E_StateOfGround/StateOfGround_E_7.svg	\
	E_StateOfGround/StateOfGround_E_8.svg	\
	E_StateOfGround/StateOfGround_E_9.svg	\
	Eprime_StateOfGround/StateOfGround_Eprime_0.svg	\
	Eprime_StateOfGround/StateOfGround_Eprime_1.svg	\
	Eprime_StateOfGround/StateOfGround_Eprime_2.svg	\
	Eprime_StateOfGround/StateOfGround_Eprime_3.svg	\
	Eprime_StateOfGround/StateOfGround_Eprime_4.svg	\
	Eprime_StateOfGround/StateOfGround_Eprime_5.svg	\
	Eprime_StateOfGround/StateOfGround_Eprime_6.svg	\
	Eprime_StateOfGround/StateOfGround_Eprime_7.svg	\
	Eprime_StateOfGround/StateOfGround_Eprime_8.svg	\
	Eprime_StateOfGround/StateOfGround_Eprime_9.svg	\
	ICAO_SigWx/Drizzle.svg	\
	ICAO_SigWx/FreezingPrecipitation.svg	\
	ICAO_SigWx/Hail.svg	\
	ICAO_SigWx/ModerateAircraftIcing.svg	\
	ICAO_SigWx/ModerateTurbulence.svg	\
	ICAO_SigWx/MountainWaves.svg	\
	ICAO_SigWx/MoutainObscuration.svg	\
	ICAO_SigWx/PressureCentreLocation.svg	\
	ICAO_SigWx/RadioactiveMaterialsInTheAtmosphere.svg	\
	ICAO_SigWx/Rain.svg	\
	ICAO_SigWx/SevereAircraftIcing.svg	\
	ICAO_SigWx/SevereSandOrDustHaze.svg	\
	ICAO_SigWx/SevereTurbulence.svg	\
	ICAO_SigWx/Shower.svg	\
	ICAO_SigWx/Snow.svg	\
	ICAO_SigWx/Thunderstorms.svg	\
	ICAO_SigWx/TropicalCyclone.svg	\
	ICAO_SigWx/VisibleVolcanicAshCloud.svg	\
	ICAO_SigWx/VolcanicEruption.svg	\
	ICAO_SigWx/WidespreadBlowingSnow.svg	\
	ICAO_SigWx/WidespreadFog.svg	\
	ICAO_SigWx/WidespreadHaze.svg	\
	ICAO_SigWx/WidespreadMist.svg	\
	ICAO_SigWx/WidespreadSandstormOrDuststorm.svg	\
	ICAO_SigWx/WidespreadSmoke.svg	\
	ICAO_SigWx/WindArrowOrFlightLevelDoubleBar.svg	\
	N_TotalCloudCover/TotalCloudCover_Automatic.svg	\
	N_TotalCloudCover/TotalCloudCover_N_0.svg	\
	N_TotalCloudCover/TotalCloudCover_N_1.svg	\
	N_TotalCloudCover/TotalCloudCover_N_2.svg	\
	N_TotalCloudCover/TotalCloudCover_N_3.svg	\
	N_TotalCloudCover/TotalCloudCover_N_4.svg	\
	N_TotalCloudCover/TotalCloudCover_N_5.svg	\
	N_TotalCloudCover/TotalCloudCover_N_6.svg	\
	N_TotalCloudCover/TotalCloudCover_N_7.svg	\
	N_TotalCloudCover/TotalCloudCover_N_8.svg	\
	N_TotalCloudCover/TotalCloudCover_N_9.svg	\
	N_TotalCloudCover/TotalCloudCover_N_Slash.svg	\
	PressureCentres/PressureCentreLocation.svg	\
	PressureCentres/TropicalCycloneNHGE.svg	\
	PressureCentres/TropicalCycloneNHLT.svg	\
	PressureCentres/TropicalCycloneSHGE.svg	\
	PressureCentres/TropicalCycloneSHLT.svg	\
	W1W2_PastWeather/PastWeather_W1W2_3a.svg	\
	W1W2_PastWeather/PastWeather_W1W2_3b.svg	\
	W1W2_PastWeather/PastWeather_W1W2_4.svg	\
	W1W2_PastWeather/PastWeather_W1W2_5.svg	\
	W1W2_PastWeather/PastWeather_W1W2_6.svg	\
	W1W2_PastWeather/PastWeather_W1W2_7.svg	\
	W1W2_PastWeather/PastWeather_W1W2_8.svg	\
	W1W2_PastWeather/PastWeather_W1W2_9.svg	\
	W1W2_PastWeather/PastWeather_W1W2_DoubleSlash.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_1.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_2.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_3.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_4.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_5.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_6.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_7.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_7a.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_7b.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_8.svg	\
	Wa1Wa2_PastWeatherAutomaticStation/PastWeatherAutomaticStation_Wa1Wa1_9.svg	\
	a_PressureTendencyCharacteristic/PressureTendencyCharacteristic_a_0.svg	\
	a_PressureTendencyCharacteristic/PressureTendencyCharacteristic_a_1.svg	\
	a_PressureTendencyCharacteristic/PressureTendencyCharacteristic_a_2.svg	\
	a_PressureTendencyCharacteristic/PressureTendencyCharacteristic_a_3.svg	\
	a_PressureTendencyCharacteristic/PressureTendencyCharacteristic_a_4.svg	\
	a_PressureTendencyCharacteristic/PressureTendencyCharacteristic_a_5.svg	\
	a_PressureTendencyCharacteristic/PressureTendencyCharacteristic_a_6.svg	\
	a_PressureTendencyCharacteristic/PressureTendencyCharacteristic_a_7.svg	\
	a_PressureTendencyCharacteristic/PressureTendencyCharacteristic_a_8.svg	\
	dw1dw1_SwellDirection/SwellDirection_dw1dw1.svg	\
	dw1dw1_SwellDirection/SwellDirection_dw1dw1_00.svg	\
	dw1dw1_SwellDirection/SwellDirection_dw1dw1_99.svg	\
	dw1dw1_SwellDirection/SwellDirection_dw1dw1_Missing.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_04.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_06.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_07.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_08.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_09.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_10.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_11.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_19.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_20.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_21.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_22.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_23.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_24.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_25.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_26.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_27.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_28.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_30.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_39.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_41.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_42.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_43.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_44.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_45.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_46.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_47.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_48.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_49.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_50.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_51.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_52.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_53.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_54.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_55.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_56.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_57.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_59.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_59a.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_59b.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_60.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_61.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_62.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_63.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_64.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_65.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_66.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_67.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_69.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_69a.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_69b.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_70.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_71.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_72.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_73.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_74.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_75.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_76.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_77.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_78.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_79.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_80.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_81.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_82.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_83.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_84.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_85.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_86.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_87.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_88.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_89.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_90.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_91.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_92.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_92a.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_92b.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_93.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_93a.svg	\
	w1w1_PresentWeatherAdditional/PresentWeatherAdditional_w1w1_93b.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_04.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_05.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_10.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_11.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_12.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_18.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_20.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_21.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_22.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_23.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_24.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_25.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_26.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_27.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_28.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_29.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_30.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_31.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_32.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_33.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_34.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_35.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_40.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_41.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_42.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_43.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_44.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_45.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_46.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_47.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_48.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_50.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_51.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_52.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_53.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_54.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_55.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_56.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_57.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_58.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_60.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_61.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_62.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_63.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_64.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_65.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_66.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_67.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_68.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_70.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_71.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_72.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_73.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_74.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_75.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_76.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_77.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_78.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_80.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_81.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_82.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_83.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_84.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_85.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_86.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_87.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_89.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_90.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_91.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_92.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_92a.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_92b.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_93.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_94.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_95.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_95a.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_95b.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_96.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_99.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_DoubleSlash.svg	\
	wawa_PresentWeatherAutomaticStation/PresentWeatherAutomaticStation_wawa_NotSignificant.svg	\
	ww_PresentWeather/PresentWeather_ww_00.svg	\
	ww_PresentWeather/PresentWeather_ww_01.svg	\
	ww_PresentWeather/PresentWeather_ww_02.svg	\
	ww_PresentWeather/PresentWeather_ww_03.svg	\
	ww_PresentWeather/PresentWeather_ww_04.svg	\
	ww_PresentWeather/PresentWeather_ww_05.svg	\
	ww_PresentWeather/PresentWeather_ww_06.svg	\
	ww_PresentWeather/PresentWeather_ww_07.svg	\
	ww_PresentWeather/PresentWeather_ww_07a.svg	\
	ww_PresentWeather/PresentWeather_ww_07b.svg	\
	ww_PresentWeather/PresentWeather_ww_08.svg	\
	ww_PresentWeather/PresentWeather_ww_09.svg	\
	ww_PresentWeather/PresentWeather_ww_10.svg	\
	ww_PresentWeather/PresentWeather_ww_11.svg	\
	ww_PresentWeather/PresentWeather_ww_12.svg	\
	ww_PresentWeather/PresentWeather_ww_13.svg	\
	ww_PresentWeather/PresentWeather_ww_14.svg	\
	ww_PresentWeather/PresentWeather_ww_15.svg	\
	ww_PresentWeather/PresentWeather_ww_16.svg	\
	ww_PresentWeather/PresentWeather_ww_17.svg	\
	ww_PresentWeather/PresentWeather_ww_18.svg	\
	ww_PresentWeather/PresentWeather_ww_19.svg	\
	ww_PresentWeather/PresentWeather_ww_20.svg	\
	ww_PresentWeather/PresentWeather_ww_21.svg	\
	ww_PresentWeather/PresentWeather_ww_22.svg	\
	ww_PresentWeather/PresentWeather_ww_23.svg	\
	ww_PresentWeather/PresentWeather_ww_24.svg	\
	ww_PresentWeather/PresentWeather_ww_25.svg	\
	ww_PresentWeather/PresentWeather_ww_26.svg	\
	ww_PresentWeather/PresentWeather_ww_27.svg	\
	ww_PresentWeather/PresentWeather_ww_28.svg	\
	ww_PresentWeather/PresentWeather_ww_29.svg	\
	ww_PresentWeather/PresentWeather_ww_30.svg	\
	ww_PresentWeather/PresentWeather_ww_31.svg	\
	ww_PresentWeather/PresentWeather_ww_32.svg	\
	ww_PresentWeather/PresentWeather_ww_33.svg	\
	ww_PresentWeather/PresentWeather_ww_34.svg	\
	ww_PresentWeather/PresentWeather_ww_35.svg	\
	ww_PresentWeather/PresentWeather_ww_36.svg	\
	ww_PresentWeather/PresentWeather_ww_37.svg	\
	ww_PresentWeather/PresentWeather_ww_38.svg	\
	ww_PresentWeather/PresentWeather_ww_39.svg	\
	ww_PresentWeather/PresentWeather_ww_40.svg	\
	ww_PresentWeather/PresentWeather_ww_41.svg	\
	ww_PresentWeather/PresentWeather_ww_42.svg	\
	ww_PresentWeather/PresentWeather_ww_43.svg	\
	ww_PresentWeather/PresentWeather_ww_44.svg	\
	ww_PresentWeather/PresentWeather_ww_45.svg	\
	ww_PresentWeather/PresentWeather_ww_46.svg	\
	ww_PresentWeather/PresentWeather_ww_47.svg	\
	ww_PresentWeather/PresentWeather_ww_48.svg	\
	ww_PresentWeather/PresentWeather_ww_49.svg	\
	ww_PresentWeather/PresentWeather_ww_50.svg	\
	ww_PresentWeather/PresentWeather_ww_51.svg	\
	ww_PresentWeather/PresentWeather_ww_52.svg	\
	ww_PresentWeather/PresentWeather_ww_53.svg	\
	ww_PresentWeather/PresentWeather_ww_54.svg	\
	ww_PresentWeather/PresentWeather_ww_55.svg	\
	ww_PresentWeather/PresentWeather_ww_56.svg	\
	ww_PresentWeather/PresentWeather_ww_57.svg	\
	ww_PresentWeather/PresentWeather_ww_58.svg	\
	ww_PresentWeather/PresentWeather_ww_59.svg	\
	ww_PresentWeather/PresentWeather_ww_60.svg	\
	ww_PresentWeather/PresentWeather_ww_61.svg	\
	ww_PresentWeather/PresentWeather_ww_62.svg	\
	ww_PresentWeather/PresentWeather_ww_63.svg	\
	ww_PresentWeather/PresentWeather_ww_64.svg	\
	ww_PresentWeather/PresentWeather_ww_65.svg	\
	ww_PresentWeather/PresentWeather_ww_66.svg	\
	ww_PresentWeather/PresentWeather_ww_67.svg	\
	ww_PresentWeather/PresentWeather_ww_68.svg	\
	ww_PresentWeather/PresentWeather_ww_69.svg	\
	ww_PresentWeather/PresentWeather_ww_70.svg	\
	ww_PresentWeather/PresentWeather_ww_71.svg	\
	ww_PresentWeather/PresentWeather_ww_72.svg	\
	ww_PresentWeather/PresentWeather_ww_73.svg	\
	ww_PresentWeather/PresentWeather_ww_74.svg	\
	ww_PresentWeather/PresentWeather_ww_75.svg	\
	ww_PresentWeather/PresentWeather_ww_76.svg	\
	ww_PresentWeather/PresentWeather_ww_77.svg	\
	ww_PresentWeather/PresentWeather_ww_78.svg	\
	ww_PresentWeather/PresentWeather_ww_79.svg	\
	ww_PresentWeather/PresentWeather_ww_80.svg	\
	ww_PresentWeather/PresentWeather_ww_81.svg	\
	ww_PresentWeather/PresentWeather_ww_82.svg	\
	ww_PresentWeather/PresentWeather_ww_83.svg	\
	ww_PresentWeather/PresentWeather_ww_84.svg	\
	ww_PresentWeather/PresentWeather_ww_85.svg	\
	ww_PresentWeather/PresentWeather_ww_86.svg	\
	ww_PresentWeather/PresentWeather_ww_87.svg	\
	ww_PresentWeather/PresentWeather_ww_88.svg	\
	ww_PresentWeather/PresentWeather_ww_89.svg	\
	ww_PresentWeather/PresentWeather_ww_90.svg	\
	ww_PresentWeather/PresentWeather_ww_91.svg	\
	ww_PresentWeather/PresentWeather_ww_92.svg	\
	ww_PresentWeather/PresentWeather_ww_93.svg	\
	ww_PresentWeather/PresentWeather_ww_93a.svg	\
	ww_PresentWeather/PresentWeather_ww_93b.svg	\
	ww_PresentWeather/PresentWeather_ww_94.svg	\
	ww_PresentWeather/PresentWeather_ww_94a.svg	\
	ww_PresentWeather/PresentWeather_ww_94b.svg	\
	ww_PresentWeather/PresentWeather_ww_95.svg	\
	ww_PresentWeather/PresentWeather_ww_95a.svg	\
	ww_PresentWeather/PresentWeather_ww_95b.svg	\
	ww_PresentWeather/PresentWeather_ww_96.svg	\
	ww_PresentWeather/PresentWeather_ww_97.svg	\
	ww_PresentWeather/PresentWeather_ww_97a.svg	\
	ww_PresentWeather/PresentWeather_ww_97b.svg	\
	ww_PresentWeather/PresentWeather_ww_98.svg	\
	ww_PresentWeather/PresentWeather_ww_99.svg	\
	ww_PresentWeather/PresentWeather_ww_DoubleSlash.svg

ICONS := $(addprefix icons-stripped/,$(ICONS))
clean:
	rm -fr png/ tmp/

dist: png
	mkdir -p tmp/$(BASENAME)
	cp -f symbols/png/*.png tmp/$(BASENAME)
	cp README.md tmp/$(BASENAME)
	cd tmp && zip $(BASENAME).zip $(BASENAME)/*.png $(BASENAME)/README.md

png:
	scripts/wws_manage.sh png

all_icons: $(ICONS)

icons-stripped: icons
	mkdir -p $@

# TODO: In the future we may want to generate the icons/* files from symbols/*,
# but it's too difficult now with the naming convention, e.g.
# symbols/a_PressureTendencyCharacteristic/WeatherSymbol_WMO_PressureTendencyCharacteristic_a_0.svg =>
# icons/a_PressureTendencyCharacteristic/PressureTendencyCharacteristic_a_0.svg

icons-stripped/%: | icons-stripped
	echo $*
	mkdir -p $(dir $@) ; \
	inkscape --batch-process --actions="select-all:all;SelectionUnGroup;select-all:all;object-stroke-to-path;select-all:all;object-to-path;select-all:all;EditSelectAllInAllLayers;SelectionUnion;select-all:all;org.inkscape.effect.filter.CleanEdges;FitCanvasToSelection;select-all:all;transform-scale:1;export-plain-svg;export-dpi:96;export-area-drawing;export-area;export-filename:$@;export-overwrite;export-do;" icons/$*

svgs2ttf:
	curl -sSL -o $@ https://raw.githubusercontent.com/fontist/svgs2ttf/master/svgs2ttf && \
	chmod +x $@

wws.ttf wws.woff wws.svg: icons.json svgs2ttf $(ICONS)
	./svgs2ttf $<
