name: build ⚙️

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies 📦
      run: sudo apt-get update -y && sudo apt-get install -y dbus dbus-user-session inkscape
    - name: Install requirements 📦
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r scripts/requirements.txt
        pip3 install flake8
    - name: run tests ⚙️
      run: |
        scripts/wws_manage.sh png
        scripts/wws_manage.sh readmes
    - name: run flake8 ⚙️
      run: flake8 scripts
